// Generated by CoffeeScript 1.4.0

/* Configuration file - Set your MySQL info here
*/


(function() {

  exports.HOSTNAME = process.env.HOSTNAME || 'localhost';

  exports.PORT = process.env.PORT || '3000';

}).call(this);
