// Generated by CoffeeScript 1.6.3
(function() {
  var app, cfg, express;

  express = require('express');

  cfg = require('./cfg/config.js');

  app = express();

  app.use(express["static"](__dirname + '/static'));

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(app.router);

  /* Controllers*/


  /* Routes*/


  app.get('/*', function(req, res) {
    return res.sendfile('index.html');
  });

  /* Start the App*/


  app.listen("" + cfg.PORT);

}).call(this);
