// Generated by CoffeeScript 1.4.0
(function() {
  var app, cfg, express;

  express = require('express');

  cfg = require('./cfg/config.js');

  app = express();

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  /* Controllers
  */


  /* Routes
  */


  /* Start the App
  */


  app.listen("" + cfg.PORT);

}).call(this);
