// Generated by CoffeeScript 1.6.3
/* boot - This is the core client application*/


(function() {
  var page;

  page = require('page');

  /* Controllers*/


  /* Models*/


  /* Routes*/


  page('/', function(ctx) {
    console.log('Homepage');
    return console.log(ctx);
  });

  page('*', function(ctx) {
    return console.log('404');
  });

  page();

}).call(this);
